codecov:
  notify:
    # Wait for both coverage jobs to finish so we don't first get a partial
    # coverage report and then, potentially quite a while later, it's updated to
    # reflect the (sort of) actual coverage, which could be confusing.
    after_n_builds: 2

# https://docs.codecov.com/docs/pull-request-comments#disable-comment
comment: false

# TODO(robinlinden): We don't want to manually have to check that tests cover new code.
#
# The coverage CI status check is only informational for now due to Bazel 7
# switching to branch coverage with gcc and gcc appearing to not generate
# reliable coverage reports when run in branch-coverage mode.
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
