codecov:
  notify:
    # Wait for both coverage jobs to finish so we don't first get a partial
    # coverage report and then, potentially quite a while later, it's updated to
    # reflect the (sort of) actual coverage, which could be confusing.
    after_n_builds: 2

# https://docs.codecov.com/docs/pull-request-comments#disable-comment
comment: false
